<h1>Review Iteration</h1>

<h2>
    Entity: <?= $this->escapeHtml($entity); ?>
    <br>
    Field: <?= $this->escapeHtml($field); ?>
    <br>
    Iteration: <?= $this->escapeHtml($iteration); ?>
</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                Primary Key
            </th>
            <th>
                Old Value
            </th>
            <th>
                New Value
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data as $row) {
    ?>
        <tr class="<?php
            if (strpos($row['newValue'], chr(15712189)) !== false) {
                echo 'danger';
            } else {
                # echo 'danger';
            }
        ?>">
            <td>
                <a href="<?= $this->url('row', array('entity' => $entity, 'primaryKey' => $primaryKey)); ?>">
                    <?= $row['primaryKey']; ?>
                </a>
            </td>
            <td>
                <?= $this->escapeHtml($row['oldValue']); ?>
            </td>
            <td>
                <?= $this->escapeHtml($row['newValue']); ?>
            </td>
        </tr>
        <tr class="<?php
            if (strpos($row['newValue'], chr(15712189)) !== false) {
                echo 'danger';
            } else {
                # echo 'danger';
            }
        ?>">
            <td>

            </td>
            <td colspan="2">
                <?= $renderer->render(new \Horde_Text_Diff(
                        'auto',
                        array(
                            explode("\n", $row['oldValue']),
                            explode("\n", $row['newValue'])
                        )
                    ); ?>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<script>
$(function() {
    $('ins').addClass('bg-success');
    $('del').addClass('bg-danger');
});
</script>