<h1>Review Entity Row Changes</h1>

<h2>
    Entity: <?= $this->escapeHtml($entity); ?>
    <br>
    Primary Key: <?= $this->escapeHtml($primaryKey); ?>
</h2>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>
                Field
            </th>
            <th>
                Iteration
            </th>
            <th>
                Old Value
            </th>
            <th>
                New Value
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($data as $row) {
    ?>
        <tr class="<?php
            if (strpos($row['newValue'], chr(15712189)) !== false) {
                echo 'danger';
            } else {
                # echo 'danger';
            }
        ?>">
            <td>
                <?= $this->escapeHtml($row['field']); ?>
            </td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('iteration', array('entity' => $entity, 'iteration' => $iteration, 'field' => $row['field'])); ?>">
                    <?= $row['iteration']; ?>
                </a>
            </td>
            <td>
                <?= $this->escapeHtml($row['oldValue']); ?>
            </td>
            <td>
                <?= $this->escapeHtml($row['newValue']); ?>
            </td>
        </tr>
        <tr class="<?php
            if (strpos($row['newValue'], chr(15712189)) !== false) {
                echo 'danger';
            } else {
                # echo 'danger';
            }
        ?>">
            <td>

            </td>
            <td colspan="2">
                <?= $renderer->render(new \Horde_Text_Diff(
                        'auto',
                        array(
                            explode("\n", $row['oldValue']),
                            explode("\n", $row['newValue'])
                        )
                    ); ?>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<table class="table">
    <caption>Current Data</caption>
    <thead>
        <tr>
            <th>
                Field
            </th>
            <th>
                Value
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($currentData as $columnName => $value) {
    ?>
        <tr>
            <td><?= $this->escapeHtml($columnName); ?></td>
            <td><?= $this->escapeHtml($value); ?></td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<script>
$(function() {
    $('ins').addClass('bg-success');
    $('del').addClass('bg-danger');
});
</script>