<?php

return [
    'Zend\Db',
    'Zend\Mvc\Console',
    'Zend\I18n',
    'Zend\Cache',
    'Zend\Paginator',
    'Zend\Session',
    'Zend\Form',
    'Zend\InputFilter',
    'Zend\Filter',
    'Zend\Hydrator',
    'Zend\Router',
    'Zend\Serializer',
    'Zend\Validator',
    'Zend\Log',
    'ZF\\DevelopmentMode',
//    'Phpro\DoctrineHydrationModule',
    'DoctrineModule',
    'DoctrineORMModule',
    'Application',
    'Database',
    'Db',
];
