<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php
            echo $this->headTitle()->prepend($this->translate('Stuki Org - Utf8Convert'))
                ->setSeparator(' - ')
                ->setAutoEscape(false)
                ;
        ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
            ->appendStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap-theme.min.css')
            ->appendStylesheet($this->basePath() . '/bower_components/font-awesome/css/font-awesome.min.css')
            ->appendStylesheet($this->basePath() . '/bower_components/angular-xeditable/dist/css/xeditable.css')
            ->appendStylesheet($this->basePath() . '/bower_components/angular-busy/dist/angular-busy.css')
            ->appendStylesheet($this->basePath() . '/css/style.css')
            ;
        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/app.js')
            ->prependFile($this->basePath() . '/bower_components/markdown/lib/markdown.js')
            ->prependFile($this->basePath() . "/bower_components/angular-busy/dist/angular-busy.js")
            ->prependFile($this->basePath() . "/bower_components/angular-xeditable/dist/js/xeditable.js")
            ->prependFile($this->basePath() . "/bower_components/angular/angular.min.js")
            ->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ;

        ?>

    </head>
    <body ng-app="utf8convert">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Utf8Convert'); ?></a>
                </div>

                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav dropdown-menu-right pull-right">
                        <?php
                        if ($this->zfcUserIdentity()) {
                        ?>
                            <?php
                            if ($this->isAllowed('administration', 'access')) {
                            ?>
                                <li class=""><a href="<?php echo $this->url('zfcadmin/zfcuseradmin/list') ?>"><?php echo $this->translate('Administration') ?></a></li>
                            <?php
                            }
                            ?>

                        <li id="user-menu" class="dropdown">
                            <a id="user-drop" class="dropdown-toggle" data-toggle="dropdown" role="button" href="#">
                                <?= $this->escapeHtml($this->zfcUserIdentity()->getDisplayName()); ?>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="user-drop" role="menu">
                                <li role="menuitem"><a href="<?php echo $this->url('zfcuser/changepassword') ?>"><?php echo $this->translate('Change Password') ?></a></li>
                                <li role="menuitem"><a href="<?php echo $this->url('zfcuser/changeemail') ?>"><?php echo $this->translate('Change Email') ?></a></li>
                                <li role="menuitem"><a href="<?php echo $this->url('zfcuser/logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                            </ul>
                        </li>
                        <?php
                        } else {
                        ?>
                            <li class=""><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Login') ?></a></li>
                        <?php
                        }
                        ?>
                    </ul>

                    <ul class="nav navbar-nav">
                        <?php
                        if ($this->zfcUserIdentity()) {
                        ?>
                            <li class=""><a href="<?php echo $this->url('visualization') ?>"><?php echo $this->translate('Data Visualization') ?></a></li>
                        <?php
                        } else {
                        ?>
                        <?php
                        }
                        ?>
                    </ul>

                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; <?php echo date('Y') ?> by Stuki Org <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
