<?php

    $this->headScript()->appendFile($this->basePath() . '/js/controller/columnController1.js');

?>

<style>
    .odd {
        background-color: #eee;
        border-top: 1px solid;
        padding: 5px;
    }

    .even {
        background-color: #fff;
        border-top: 1px solid;
        padding: 5px;
    }

    .data-odd {
        background-color: #eef;
        border-top: 1px solid;
        padding: 5px;
    }

    .data-even {
        background-color: #ddf;
        border-top: 1px solid;
        padding: 5px;
    }
</style>

<div class="pull-right">
    Data Type: <?= $this->escapeHtml($this->column->getDataType()); ?>
    <br>
    Length: <?= $this->escapeHtml($this->column->getLength()); ?>
    <br>
    Default Value: <?= $this->escapeHtml($this->column->getDefaultValue()); ?>
    <br>
    Is Nullable: <?= ($this->column->getIsNullable()) ? 'YES': 'NO'; ?>
    <br>
    Extra: <?= $this->escapeHtml($this->column->getExtra()); ?>
</div>

<h1>
    Conversion
    <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
        <?= $this->escapeHtml($conversion->getName()); ?>
    </a>
</h1>

<h3>
    <?= $this->escapeHtml($this->column->getTableDef()->getName()); ?>.<?= $this->escapeHtml($this->column->getName()); ?>
</h3>

<div ng-controller="columnController" ng-init="columnModel.init('<?= $this->basePath(); ?>', <?= $conversion->getId(); ?>, <?= $column->getId(); ?>)">
<div cg-busy="columnPromise"></div>

Page {{ dataPoint.page || 0 }} of {{ dataPoint.page_count || 0 }}
<pagination page="1" max-size="20" total-items="1000" items-per-page="50"></pagination>

<ul class="pagination center-block">
    <li ng-repeat="(name, link) in dataPoint._links">
        <a href="#" ng-click="columnModel.load(link.href)">{{ name }}</a>
    </li>
</ul>

<span class="pull-right btn-group">
    <a href="#" class="btn btn-default" ng-click="columnModel.flagAll('approved')">
        <i class="glyphicon glyphicon-ok"></i> All
    </a>

    <a href="#" class="btn btn-default" ng-click="columnModel.flagAll('flagged')">
        <i class="glyphicon glyphicon-flag"></i> All
    </a>

    <a href="#" class="btn btn-default" ng-click="columnModel.flagAll('denied')">
        <i class="glyphicon glyphicon-remove"></i> All
    </a>

    <a href="#" class="btn btn-default" ng-click="columnModel.showAllComments()">
        <i class="glyphicon glyphicon-comment"></i> Show
    </a>

    <a href="#" class="btn btn-default" ng-click="columnModel.hideAllComments()">
        <i class="glyphicon glyphicon-comment"></i> Hide
    </a>
    <a href="#" class="btn btn-danger" onClick="if (confirm('Are you sure?')) $('.copy').click();" title="Copy All Old Value to New Value">
        <i class="glyphicon glyphicon-hand-right"></i> Copy All
    </a>
</span>

<div class="container text-left" style="clear: both;">
    <div class="col-md-1">
        <strong>#</strong>
    </div>

    <div class="col-md-4">
        <strong>Old Value</strong>
    </div>

    <div class="col-md-4">
        <strong>New Value</strong>
    </div>

    <div class="col-md-3 text-right">
        <strong>Actions & Comment</strong>
    </div>
</div>

<div class="container" ng-repeat="dataPoint in dataPoint._embedded.data_point" ng-class-odd="'odd'" ng-class-even="'even'">

    <div class="col-md-1">
        {{ dataPoint.primaryKey }}
        <br>
        <b
            ng-hide="!dataPoint._showComment"
        >Comment</b>
    </div>

    <div class="col-md-4">
		<a 
			class="btn btn-default copy"
			title="Copy Old Value to New Value"
			ng-click="columnModel.update(dataPoint, {'newValue': dataPoint.oldValue})"
		>
            <i class="glyphicon glyphicon-hand-right"></i>
		</a>
        {{ dataPoint.oldValue }}
        <br style="clear: both">
        <span
            ng-hide="!dataPoint._showComment"
            class="ng-hide"
            onbeforesave="columnModel.update(dataPoint, {'comment': $data})"
            editable-textarea="dataPoint.comment"
            e-rows="4"
            e-cols="40"
        >{{ dataPoint.comment || 'no comment' }}</span>

    </div>

    <div class="col-md-4">
        <span
            onbeforesave="columnModel.update(dataPoint, {'newValue': $data})"
            editable-textarea="dataPoint.newValue"
            onshow="columnModel.addConvertButton()"
        >{{ dataPoint.newValue || "no data"}}</span>
    </div>

    <div class="col-md-3 text-right">
                <span class="btn-group pull-right">
                    <a
                        class="btn"
                        title="Mark as Approved"
                        ng-class="(dataPoint.approved) ? 'btn-success': 'btn-default'"
                        ng-click="
                            columnModel.update(dataPoint, {'approved': !dataPoint.approved, 'flagged': false, 'denied': false});
                        ">
                        <i class="glyphicon glyphicon-ok"></i>
                    </a>

                    <a
                        class="btn"
                        title="Mark as Flagged"
                        ng-class="(dataPoint.flagged) ? 'btn-warning': 'btn-default'"
                        ng-click="
                            columnModel.update(dataPoint, {'flagged': !dataPoint.flagged, 'approved': false, 'denied': false});
                        ">
                        <i class="glyphicon glyphicon-flag"></i>
                    </a>

                    <a
                        class="btn"
                        title="Mark as Denied"
                        ng-class="(dataPoint.denied) ? 'btn-danger': 'btn-default'"
                        ng-click="
                            columnModel.update(dataPoint, {'denied': !dataPoint.denied, 'flagged': false, 'approved': false});
                        ">
                        <i class="glyphicon glyphicon-remove"></i>
                    </a>

                    <a
                        class="btn"
                        title="Toggle live data view"
                        ng-class="
                        {
                            'btn-default': !dataPoint.data,
                            'btn-info': dataPoint.data && !dataPoint._showData,
                            'btn-primary': dataPoint.data && dataPoint._showData
                        }
                        "
                        ng-click="
                            columnModel.data(dataPoint);
                        ">
                        <i class="glyphicon glyphicon-list-alt"></i>
                    </a>

                    <a
                        class="btn btn-default"
                        title="View URL"
                        ng-click="columnModel.openUrl(dataPoint);"
                        >
                        <i class="glyphicon glyphicon-link"></i>
                    </a>

                    <a
                        class="btn"
                        title="Edit comment"
                        ng-class="
                        {
                            'btn-default': !dataPoint.comment,
                            'btn-info': dataPoint.comment && !dataPoint._showComment,
                            'btn-primary': dataPoint.comment && dataPoint._showComment
                        }
                    " ng-click="dataPoint._showComment = !dataPoint._showComment">
                        <i class="glyphicon glyphicon-comment"></i>
                    </a>
                </span>
    </div>

    <div class="col-md-12 ng-hide"
        ng-hide="!dataPoint._showData"
    >
        <div class="col-md-1"></div>
        <div class="col-md-2">
            <strong>Column Name</strong>
        </div>
        <div class="col-md-4">
            <strong>Value</strong>
        </div>
        <div class="col-md-4">
            <strong>New Value</strong>
        </div>
        <div class="col-md-1"></div>
    </div>

    <div class="col-md-12 ng-hide"
        ng-hide="!dataPoint._showData"
        ng-repeat="row in dataPoint.data._embedded"
        ng-class-odd="'data-odd'" ng-class-even="'data-even'"
    >
        <div class="col-md-1"></div>
        <div class="col-md-2">
            {{ row._embedded.columnDef.name }}
        </div>
        <div class="col-md-4">
            {{ row.oldValue }}
        </div>
        <div class="col-md-4">
            <span onbeforesave="columnModel.update(row, {'newValue': $data})" editable-textarea="row.newValue">{{ row.newValue }}</span>
        </div>
        <div class="col-md-1"></div>
    </div>

    <div class="col-md-12 ng-hide"
        ng-hide="!dataPoint._showData"
        ng-repeat="(column, value) in dataPoint.data"
        ng-if="column != '_embedded'"
        ng-class-odd="'data-odd'" ng-class-even="'data-even'"
    >
        <div class="col-md-1"></div>
        <div class="col-md-2">
            {{ column }}
        </div>
        <div class="col-md-8">
            <span onbeforesave="columnModel.create(dataPoint, column, value, $data)" editable-textarea="value" e-rows="4" e-cols="40">{{ value || 'no data' }}</span>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

</div>
