<?php

    $this->headScript()->appendFile($this->basePath() . '/js/controller/columnController.js');

?>
<h1>
    Conversion
    <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
        <?= $this->escapeHtml($conversion->getName()); ?>
    </a>
</h1>

<h2>
    <?= $this->escapeHtml($this->column->getTableDef()->getName()); ?>.<?= $this->escapeHtml($this->column->getName()); ?>
</h2>

<div class="container">
    <div class="col-md-2">
        Data Type: <?= $this->escapeHtml($this->column->getDataType()); ?>
    </div>
    <div class="col-md-2">
        Length: <?= $this->escapeHtml($this->column->getLength()); ?>
    </div>
    <div class="col-md-2">
        Default Value: <?= $this->escapeHtml($this->column->getDefaultValue()); ?>
    </div>
    <div class="col-md-2">
        Is Nullable: <?= ($this->column->getIsNullable()) ? 'YES': 'NO'; ?>
    </div>
    <div class="col-md-2">
        Extra: <?= $this->escapeHtml($this->column->getExtra()); ?>
    </div>
</div>

<div ng-controller="columnController" ng-init="columnModel.init('<?= $this->url('database-api.rest.doctrine.data-point'); ?>', <?= $conversion->getId(); ?>, <?= $column->getId(); ?>)">
<div cg-busy="columnPromise"></div>

<table class="table table-striped table-hover">
    <caption>
        <b>Page {{ dataPoint.page }} of {{ dataPoint.page_count }}</b>

        <ul class="pagination center-block">
            <li ng-repeat="(name, link) in dataPoint._links">
                <a href="#" ng-click="columnModel.load(link.href)">{{ name }}</a>
            </li>
        </ul>


        <span class="pull-right btn-group">
            <a href="#" class="btn btn-default" ng-click="columnModel.showAllComments()">Show <i class="glyphicon glyphicon-comment"></i>
</a>
            <a href="#" class="btn btn-default" ng-click="columnModel.hideAllComments()">Hide <i class="glyphicon glyphicon-comment"></i>
</a>
        </span>
    </caption>
    <thead>
        <tr>
            <th>
                Primary Key string
            </th>
            <th>
                Old Value
            </th>
            <th>
                New Value
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        <tr ng-repeat="dataPoint in dataPoint._embedded.data_point" ng-class-odd="'odd'" ng-class-even="'even'">
            <td>
                {{ dataPoint.primaryKey }}
            </td>
            <td>
                {{ dataPoint.oldValue }}
            </td>
            <td>
                <span onbeforesave="columnModel.update(dataPoint, {'newValue': $data})" editable-textarea="dataPoint.newValue" e-rows="8" e-cols="80">{{ dataPoint.newValue }}</span>
            </td>
            <td>
                <span class="btn-group pull-right">
                    <a class="btn" ng-class="(dataPoint.flagged) ? 'btn-danger': 'btn-default'"
                        ng-click="
                            columnModel.update(dataPoint, {'flagged': !dataPoint.flagged, 'approved': false});
                        ">
                        <i class="glyphicon glyphicon-flag"></i>
                    </a>
                    <a class="btn btn-default" ng-class="(dataPoint.approved) ? 'btn-success': 'btn-default'"
                        ng-click="
                            columnModel.update(dataPoint, {'approved': !dataPoint.approved, 'flagged': false});
                        ">
                        <i class="glyphicon glyphicon-ok"></i>
                    </a>

                    <a class="btn" ng-class="(dataPoint.comment) ? 'btn-info': 'btn-default'" ng-click="dataPoint._showComment = !dataPoint._showComment">
                        <i class="glyphicon glyphicon-comment"></i>
                    </a>
                </span>

                <br style="clear: both;">

                <span ng-hide="!dataPoint._showComment" class="ng-hide pull-right" onbeforesave="columnModel.update(dataPoint, {'comment': $data})" editable-textarea="dataPoint.comment" e-rows="4" e-cols="40">{{ dataPoint.comment || 'no comment' }}</span>
            </td>
        </tr>
    </tbody>
</table>

</div>