<h1>
    Conversion
    <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
        <?= $this->escapeHtml($conversion->getName()); ?>
    </a>
</h1>

<?php
foreach ($conversion->getTableDef() as $table) {
    $totalDataPoint = 0;
    foreach ($table->getColumnDef() as $column) {
        $totalDataPoint += $this->countDataPoint($conversion, $column);
    }
    if (!$totalDataPoint) {
        continue;
    }
?>
<table class="table table-striped table-hover">
    <caption>Table <?= $this->escapeHtml($table->getName()); ?></caption>
    <thead>
        <tr>
            <th>
                Column
            </th>
            <th>
                Data Type
            </th>
            <th>
                Length
            </th>
            <th>
                Data Points
            </th>
            <th>
                Not Reviewed
            </th>
            <th>
                Approved
            </th>
            <th>
                Flagged
            </th>
            <th>
                Denied
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($table->getColumnDef() as $column) {
        $totalDataPoint = $this->countDataPoint($conversion, $column);
        if (!$totalDataPoint) {
            continue;
        }
    ?>
        <tr>
            <td>
                <a href="<?= $this->url('visualization/conversion/column',
                    array('conversion_id' => $conversion->getId(),
                    'column_id' => $column->getId())); ?>">
                        <?= $this->escapeHtml($column->getName()); ?>
                </a>
            </td>
            <td>
                <?= $this->escapeHtml($column->getDataType()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($column->getLength()); ?>
            </td>
            <td>
                <?= $this->countDataPoint($conversion, $column); ?>
            </td>
            <td>
                <?= $this->countDataPointNotReviewed($conversion, $column); ?>
            </td>
            <td>
                <?= $this->countDataPointApproved($conversion, $column); ?>
            </td>
            <td>
                <?= $this->countDataPointFlagged($conversion, $column); ?>
            </td>
            <td>
                <?= $this->countDataPointDenied($conversion, $column); ?>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}
?>
