<h1>
    Conversion
    <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
        <?= $this->escapeHtml($conversion->getName()); ?>
    </a>
</h1>

<?php
foreach ($conversion->getTableDef() as $table) {
    $totalDataPoint = 0;
    foreach ($table->getColumnDef() as $column) {
        $totalDataPoint += $this->countDataPoint($conversion, $column, false);
        $totalDataPoint += $this->countDataPoint($conversion, $column, true);
    }
    if (!$totalDataPoint) {
        continue;
    }
?>
<table class="table table-striped table-hover">
    <caption>Table <?= $this->escapeHtml($table->getName()); ?></caption>
    <thead>
        <tr>
            <th>
                Column
            </th>
            <th>
                Data Type
            </th>
            <th>
                Length
            </th>
            <th>
                Data Points
            </th>
            <th>
                Not Reviewed
            </th>
            <th>
                Approved
            </th>
            <th>
                Flagged
            </th>
            <th>
                Denied
            </th>
            <th>
                Imported
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($table->getColumnDef() as $column) {
        $totalDataPoint = $this->countDataPoint($conversion, $column, false);
        $totalDataPoint += $this->countDataPoint($conversion, $column, true);
        if (!$totalDataPoint) {
            continue;
        }
    ?>
        <tr>
            <td>
                <a href="<?= $this->url('visualization/conversion/column',
                    array('conversion_id' => $conversion->getId(),
                    'column_id' => $column->getId())); ?>">
                        <?= $this->escapeHtml($column->getName()); ?>
                </a>
            </td>
            <td>
                <?= $this->escapeHtml($column->getDataType()); ?>
            </td>
            <td>
                <?= $this->escapeHtml($column->getLength()); ?>
            </td>
            <td>
                <?= $this->countDataPoint($conversion, $column, false) + $this->countDataPoint($conversion, $column, true); ?>
            </td>
            <td
                class="<?=
                ($this->countDataPointNotReviewed($conversion, $column, false))
                    ? 'info': '';
                ?>"
            >
                <?= $this->countDataPointNotReviewed($conversion, $column, false); ?>
            </td>
            <td
                class="<?=
                ($this->countDataPointApproved($conversion, $column, false))
                    ? 'success': '';
                ?>"
            >
                <?= $this->countDataPointApproved($conversion, $column, false); ?>
            </td>
            <td
                class="<?=
                ($this->countDataPointFlagged($conversion, $column, false))
                    ? 'warning': '';
                ?>"
            >
                <?= $this->countDataPointFlagged($conversion, $column, false); ?>
            </td>
            <td
                class="<?=
                ($this->countDataPointDenied($conversion, $column, false))
                    ? 'danger': '';
                ?>"
            >
                <?= $this->countDataPointDenied($conversion, $column, false); ?>
            </td>
            <td
                class="<?=
                ($this->countDataPointApproved($conversion, $column, true))
                    ? 'info': '';
                ?>"
            >
                <?= $this->countDataPointApproved($conversion, $column, true); ?>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}
?>

<?php
if ($this->isAllowed('administration', 'access')) {
?>
<a class="btn btn-large btn-primary" href="<?=
    $this->url('visualization/conversion/import', array('conversion_id' => $conversion->getId())); ?>">Import Approved</a>
<?php
}
?>