<h1>Conversion</h1>

<h2><?= $this->escapeHtml($conversion->getName()); ?></h2>

<?php
foreach ($conversion->getTableDef() as $table) {
?>
<table class="table table-striped table-hover">
    <caption><?= $this->escapeHtml($table->getName()); ?></caption>
    <thead>
        <tr>
            <th>
                Column
            </th>
            <th>
                Data Type
            </th>
            <th>
                Length
            </th>
            <th>
                Data Points
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($table->getColumnDef() as $column) {
    ?>
        <tr>
            <th>
                <?= $this->escapeHtml($column->getName()); ?>
            </th>
            <th>
                <?= $this->escapeHtml($column->getDataType()); ?>
            </th>
            <th>
                <?= $this->escapeHtml($column->getLength()); ?>
            </th>
            <th>
                <a class="btn btn-default" href="<?= $this->url('visualization/conversion/column',
                    array('conversion_id' => $conversion->getId(),
                    'column_id' => $column->getId())); ?>">
                    <?= $this->countDataPoint($conversion, $column); ?>
                </a>
            </th>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
<?php
}
?>
