<h1>Data Visualization</h1>

<table class="table table-striped table-hover">
    <caption>Conversions</caption>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Tables
            </th>
            <th>
                Created At
            </th>
            <th>
                Completed At
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($conversions as $conversion) {
    ?>
        <tr>
            <th>
                <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
                    <?= $this->escapeHtml($conversion->getName()); ?>
                </a>
            </th>
            <th>
                <?php
                foreach ($conversion->getTableDef() as $table) {
                ?>
                    <a class="btn btn-default" href="<?= $this->url('visualization/conversion/table', array(
                        'table_id' => $table->getId(),
                        'conversion_id' => $conversion->getId()));
                    ?>">
                        <?= $this->escapeHtml($table->getName()); ?>
                    </a>
                <?php
                }
                ?>
            </th>
            <th>
                <?= $conversion->getCreatedAt()->format('Y-m-d H:i:s'); ?>
            </th>
            <th>
                <?= $conversion->getCompletedAt()->format('Y-m-d H:i:s'); ?>
            </th>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
