<?php

error_reporting(0);
ini_set('display_errors', true);
?>
<h1>Data Visualization</h1>

<table class="table table-striped table-hover">
    <caption>Conversions</caption>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Tables
            </th>
            <th>
                Data Points
            </th>
            <th>
                Created At
            </th>
            <th>
                Conversion Started At
            </th>
            <th>
                Conversion Ended At
            </th>
        </tr>
    </thead>
    <tbody>
    <?php
    foreach ($conversions as $conversion) {
    ?>
        <tr>
            <th>
                <a href="<?= $this->url('visualization/conversion', array('conversion_id' => $conversion->getId())); ?>">
                    <?= $this->escapeHtml($conversion->getName()); ?>
                </a>
            </th>
            <th>
                <?php
                foreach ($conversion->getTableDef() as $table) {
                    $totalDataPoint = 0;
                    foreach ($table->getColumnDef() as $column) {
                        $totalDataPoint += $this->countDataPoint($conversion, $column);
                    }
                    if (!$totalDataPoint) {
                        continue;
                    }
                ?>
                    <a class="btn btn-default" href="">
                        <?= $this->escapeHtml($table->getName()); ?>
                    </a>
                <?php
                }
                ?>
            </th>
            <th>
                <?php
                    echo $conversion->getDataPointCount();
                ?>
            </th>
            <th>
                <?= $conversion->getCreatedAt()->format('Y-m-d H:i:s'); ?>
            </th>
            <th>
                <?php
                if ($conversion->getStartAt()) {
                ?>
                <?= $conversion->getStartAt()->format('Y-m-d H:i:s'); ?>
                <?php
                }
                ?>
            </th>
            <th>
                <?php
                if ($conversion->getEndAt()) {
                ?>
                <?= $conversion->getEndAt()->format('Y-m-d H:i:s'); ?>
                <?php
                }
                ?>
            </th>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>

<table class="table">
    <caption>Table Options</caption>
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                URL Pattern
            </th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($this->tables as $table) {
        ?>
            <tr>
                <td>
                    <a href="<?= $this->url('visualization/table', array('table_id' => $table->getId())); ?>">
                        <?= $this->escapeHtml($table->getName()); ?>
                    </a>
                </td>
                <td><?= $this->escapeHtml($table->getUrl()); ?></td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>