<h1>
    Table Options for <?= $this->escapeHtml($this->table->getName()); ?>
</h1>

<table class="table">
    <caption>Primary Key(s)</caption>
    <tbody>
        <?php foreach ($this->table->getPrimaryKeyDef() as $primaryKey) {
        ?>
            <tr>
                <td>
                    <?= $this->escapeHtml($primaryKey->getName()); ?>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<p>
    You may use any of the primary keys to construct your URL.
</p>

<p>
    Example URL: <i>http://db.etree.org/db/shows/browse/artist_key/&lt;artist_key&gt;</i>
</p>

<form method="post" action="<?= $this->url('visualization/table', array('table_id' => $this->table->getId())); ?>">
    <label for="url">URL</label>
    <input type="text" size="80" name="url" value="<?= $this->escapeHtml($this->table->getUrl()); ?>">

    <input type="submit" class="btn btn-default" value="Save">
</form>

